spring:
  datasource:
    url: ${jdbcURL}
    password: ${jdbcPassword}
    username: ${jdbcUsername}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false